FROM ubuntu:22.04
RUN apt-get update && apt-get install -y python3.9 python3.9-pip
COPY requirements.txt .
RUN pip3 install -r requirements.txt
RUN apt-get clean && apt-get autoremove
COPY . .
CMD ["python3.9", "app.py"]